# organization name, it's used to get github repo url, also in page title
name: yoshuawuyts

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       Yoshua Wuyts
description: npm modules
keywords:    badgeboard, repo-utils

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - barracks
 - customs
 - ensemble
 - newspeak
 - react-anchor
 #- ensemble-dom
 - simple-local
 - simple-store
 - object-apply
 - object-emitter-only
 - fax
 #- slowdrip
 - event-accessor
 #- keanu
 - dad
 - degrees-radians
 - miller
 - slugificate
 - attendant
 - foyer
 - object-join
 - factory-bro
 - wayfarer

# list of maintainers, this won't be sorted
maintainers:
 - name:    Yoshua Wuyts
   github:  yoshuawuyts   # github account, required: we link to it
   npm:     yoshuawuyts   # npm account, required to determine lead maintainer
   twitter: yoshuawuyts   # twitter account, optional
   gittip:  yoshuawuyts   # gittub badge, optional
   email:   i@yoshuawuyts.com

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
